#!/bin/sh

case "$1" in
    start)
        mkdir -p /dev
        echo "[init] starting amp-hart0-app"
        /usr/bin/amp-hart0-app &
        ;;
    stop)
        killall amp-hart0-app 2>/dev/null || true
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
