#ifndef WORKSHOP_PROTOCOL_H
#define WORKSHOP_PROTOCOL_H

#include <stdint.h>

#define WORKSHOP_FAULT_OVER_TEMP 0x01u
#define WORKSHOP_FAULT_OVER_CURRENT 0x02u
#define WORKSHOP_FAULT_OVER_VOLTAGE 0x04u
#define WORKSHOP_FAULT_UNDER_VOLTAGE 0x08u
#define WORKSHOP_FAULT_BREAKER_OPEN 0x10u
#define WORKSHOP_FAULT_SENSOR_INVALID 0x20u

#define WORKSHOP_STATUS_UNKNOWN_COMMAND 0x80000000u

#define WORKSHOP_CMD_NOOP 0u
#define WORKSHOP_CMD_START 1u
#define WORKSHOP_CMD_STOP 2u
#define WORKSHOP_CMD_RESET 3u
#define WORKSHOP_CMD_MODE_NORMAL 4u
#define WORKSHOP_CMD_MODE_FAST 5u
#define WORKSHOP_CMD_SET_CURRENT 6u
#define WORKSHOP_CMD_SET_VOLTAGE 7u

#define WORKSHOP_SENSOR_PERIOD_MS 100u
#define WORKSHOP_STATUS_PERIOD_MS 200u
#define WORKSHOP_SAFETY_PERIOD_MS 200u
#define WORKSHOP_CHARGE_PERIOD_MS 200u
#define WORKSHOP_COMMAND_PERIOD_MS 500u

#define WORKSHOP_NORMAL_CURRENT_LIMIT_MA 6000u
#define WORKSHOP_FAST_CURRENT_LIMIT_MA 10000u
#define WORKSHOP_NORMAL_VOLTAGE_LIMIT_MV 12000u
#define WORKSHOP_FAST_VOLTAGE_LIMIT_MV 13200u

#define WORKSHOP_MIN_VOLTAGE_MV 10000u
#define WORKSHOP_MAX_VOLTAGE_MV 14000u
#define WORKSHOP_MAX_CURRENT_MA 12000u
#define WORKSHOP_MAX_TEMP_C 45.0f

#define WORKSHOP_SAFETY_MAX_CURRENT_MA 11000u
#define WORKSHOP_SAFETY_MAX_VOLTAGE_MV 13500u

#endif
